### ISSUE TITLE
ES-Carbon Theme Final Review

### ISSUE THREAD

**Issue by HerbFargus** [RetroPie/RetroPie-Setup#1021]
@petrockblog @joolswills Just opening a ticket for you to review the Carbon theme for the next point release.

https://github.com/HerbFargus/es-theme-carbon

Can also be installed from the setup script.

I've tested it with all 51 systems with default memory split and no white screen of death or blocked text. 

Props to Rookervik as he made it all. I just did minor coding and hosted it as a  repo.

![system2](https://cloud.githubusercontent.com/assets/10035308/10036605/05c0db54-6167-11e5-81b0-55c313df3180.png)

![system3](https://cloud.githubusercontent.com/assets/10035308/10037515/70d06cae-6174-11e5-9483-478f14a90efc.png)

**Comment by joolswills** [comment]
I am in support of this theme - we have a lot of tickets due to people being out of gpu allocated memory due to the backgrounds etc in the simple theme - the simple theme is pretty - but requires ram. 

The carbon theme has the retropie branding, but is also elegant and stylish in a way that is memory efficient - so I would back using it as the default. :) Basically a static background, with a similar horizontal nav, but with very good looking vector images reflected above the navigation per platform.

+1 from me.

**Comment by gr33k** [comment]
+1 from me - Works fine on my RasPi B+ with 32 icons - nothing missing :)

I tried the carbon and the carbon-centered versions. Both worked fine, but I opt for the standard Carbon theme as default candidate.

I DO love the Simple Theme - but I can’t use it on my Pi. So 100% agree with the static background.

-- 
Paul

On September 22, 2015 at 6:03:04 PM, Jools Wills (notifications@github.com) wrote:

I am in support of this theme - we have a lot of tickets due to people being out of gpu allocated memory due to the backgrounds etc in the simple theme - the simple theme is pretty - but requires ram.

The carbon theme has the retropie branding, but is also elegant and stylish in a way that is memory efficient - so I would back using it as the default. :) Basically a static background, with a similar horizontal nav, but with very good looking vector images reflected above the navigation per platform.

+1 from me.

**Comment by Haris1977** [comment]
+1

It should be the default theme :)

**Comment by petrockblog** [comment]
This theme looks awesome and the technical advantages that Jools also pointed out above make it a great candidate as new default theme.

+1 from me as well.

**Comment by joolswills** [comment]
ok so all decided - we will switch to the theme (for new installs). Thanks everyone :) Will get this sorted over the next few days.

**Comment by HerbFargus** [comment]
as of commit https://github.com/RetroPie/RetroPie-Setup/commit/05a665ddf49cb470084f54af850d3bf47f293121 we can consider this resolved. Thanks

**Comment by Haris1977** [comment]
Can anyone also create a "steam" theme folder (for carbon theme) ? Check out my edit 2 in my 2nd post here for more details about that:

https://github.com/RetroPie/RetroPie-Setup/issues/1082#issuecomment-156080005
