### ISSUE TITLE
Slow System Shutdown

### ISSUE THREAD

**Issue by partyguy2016** [RetroPie/RetroPie-Setup#1200]
The 3.4 system shutdown time is much slower than 3.3.  Is this an error?  It takes about 3 min. It was pretty much instant on 3.3.

**Comment by bengus64** [comment]
I think this is because of the changes in the way the metadata is written each time you shutdown (being written to emulationstation), The more roms you have, the longer it will take. I think I have close to 12,000 total roms on my card, and a shutdown takes about 8 minutes. I could be wrong though, either way its a small price to pay for the new feature imo.

**Comment by joolswills** [comment]
Yeah, it's not a bug. Before when restarting/shutting down ES got killed without shutting down correctly as it would when you "quit" meaning people lost their meta data edits etc. This is now corrected but if you have a lot of games it can take a little while.

**Comment by robertybob** [comment]
@joolswills Quick question, is there a simple way for me stop any kind of saving on shutdown? All my gamelists are complete and I have no interest in number of times played or last played  data.

**Comment by joolswills** [comment]
currently - press ctrl+c

**Comment by joolswills** [comment]
(you might kill the script too - or you can create your own reboot script or something)
