### ISSUE TITLE
Berryboot image is unstable

### ISSUE THREAD

**Issue by nerdythor** [RetroPie/RetroPie-Setup#1406]
Hey all-- I'd been playing retropie without any issues for a few weeks now off of my SD card. I decided to go ahead and use berryboot to install it to a solid state drive. When I went to do this the pi has consistently crashed during gameplay. The last message I get in syslogs is 

Mar 27 06:17:26 retropie systemd[1]: bluetooth.service: main process exited, code=killed, status=9/KILL
Mar 27 06:17:26 retropie systemd[1]: Unit bluetooth.service entered failed state

Are there any plans to update the bluetooth drivers for the berryboot image or is this an issue with berryboot/raspbian itself?

**Comment by joolswills** [comment]
The BerryBoot kernel is managed by BerryBoot. You don't specify what hardware you are using but there are known issues with RPI3 and bluetooth with PS3 controllers - https://github.com/raspberrypi/linux/issues/1360

Please use the forum first for help as you are more likely to find someone with a similar hardware configuration then - and often the problem is the underlying OS and not retropie https://retropie.org.uk/forum/
