### ISSUE TITLE
added support for colecovision in libretro blue-msx

### ISSUE THREAD

**Issue by bigboo3000** [RetroPie/RetroPie-Setup#2032]
Hi
FIY colecovision support have been added in libretro:
https://github.com/libretro/blueMSX-libretro/pull/41#event-1148586688

**Comment by joolswills** [comment]
Thanks. You can install from source to get the latest code. Binaries will be updated soon.

**Comment by joolswills** [comment]
(I will look into adding the emulator as an optional emulator for coleco also - but it needs some testing first). Happy for anyone to test and report back (the forum would be the best place for this).

**Comment by joolswills** [comment]
I gave it a quick test. Unfortunately it doesn't automatically switch to colecovision when loading a colecovision rom - you need to manually change the core options.

Because we share the core options between all systems, this is a problem as we can't set it to colecovision without it defaulting to that if loading MSX games. Ideally it would autodetect - this would need to be changed in the libretro code.

**Comment by joolswills** [comment]
If we had core options per system this could work around it. I have thought about doing this before, but it would mean old core options would be lost if we switched. Something I would want to discuss on the forum.

**Comment by joolswills** [comment]
Should be possible to force a different core options just for this system - which I will test. Not ideal, but should make it work.
