### ISSUE TITLE
psx bios is not working

### ISSUE THREAD

**Issue by BoBBer446** [RetroPie/RetroPie-Setup#2311]
how i can change the md5 hash for bios?
i tryed more then 10 different bios for psx but no file is working :S

**Comment by movisman** [comment]
You need to post an issue on the forum regarding this, rather than on github. Some more details such as the emulator you are using would be helpful.

Make sure you follow all instructions here:
https://github.com/retropie/retropie-setup/wiki/Playstation-1

If you have the correct PSX BIOS, it will work fine.

**Comment by BoBBer446** [comment]
i tryed a lot of different files for 5500,5501,5502 from different sources but no file is working.
I read your ling and hope i find a soluten. Maybe something is wrong. The psx .bin files also not shown

i try to run lr-beetle-psx

**Comment by joolswills** [comment]
Please use the forum as directed.
