### ISSUE TITLE
USB GamePad driver name has a question mark (?) at the beginning, and isn't being saved properly

### ISSUE THREAD

**Issue by ymgenesis** [RetroPie/RetroPie-Setup#2392]
Running the latest RetroPie on Ubuntu 16.04TLS
I recently bought a N64-to-USB adapter which allows two controllers to be plugged in:
https://www.amazon.ca/MAYFLASH-N64-Controller-Adapter-Pc/dp/B002B9FIUU/ref=sr_1_1?ie=UTF8&qid=1525125178&sr=8-1&keywords=N64+usb+adapter

The emulationstation input configuration comes up fine, and all the buttons map successfully.
The issue, however, is that the gamepad adapter driver/name has a '?' at the start of its name, and emulationstation can't save the controller's /opt/retropie/configs/all/retroarch-joypads/ entry.

![Here's a shot of the es_temporaryinput.cfg file](https://user-images.githubusercontent.com/25252829/39452424-379f4846-4ca0-11e8-9fd4-28518fdd93db.png)

Furthermore, I haven't been able to get the controller config'd with retroarch. I've looked at the documentation. I think it has something to do with the actual buttons on the controller not actually being the logical buttons maintained by retroarch.

Any help would be very much appreciated!
All the best

**Comment by joolswills** [comment]
Nothing I can do about this currently due to the limitations of the tools we use to create/parse the xml. You will have to construct a retroarch controller config manually and ES config (you can use the `/opt/retropie/configs/all/emulationstation/temporaryinput.cfg and copy the input section into the es_input.cfg). Or alternatively look for another adapter that doesn't put non ascii characters in  their device names.
