### ISSUE TITLE
Please add gamepad support and directions to enable it in Maldita Castilla

### ISSUE THREAD

**Issue by cpoliticas** [RetroPie/RetroPie-Setup#2884]
It seems that Maldita Castilla has a good gamepad support for steam and xbox platforms (https://steamcommunity.com/app/534290/discussions/0/1732089092437580532/) but for Raspberry Pi is very difficult to connect a joypad or only very few devices are supported.  You can see this topic discussed in the retropie forums in here https://retropie.org.uk/forum/topic/3578/maldita-castilla-joypad-support and here https://retropie.org.uk/forum/topic/15116/maldita-castilla-on-raspberry-pi-joystick-controls

Some of the people who attempted and succeeded using a gamepad for Maldita Castilla are using very specific hardware or the directions are confusing to follow for those with a more generic hardware like a 8bitdo controller, for instance.  Please, add support for a wider range of devices or post some clear directions to make it easier to set up.

Thank you very much!

**Comment by cmitu** [comment]
You should use the forum for support questions, as directed in the issue template. Raspberry Pi supports a multitude of controllers, so that's not a problem of device support, but more likely configuration. Btw, the game you linked (Maldita Castilla EX) is not the same as the one available for the PI.
