### ISSUE TITLE
KDE Neon 20.04 rejected as "unsupported OS"

### ISSUE THREAD

**Issue by Taranchul** [RetroPie/RetroPie-Setup#3276]
Hi, Clyde from retropie.org.uk/forum here.

when installing following [these instructions](https://retropie.org.uk/docs/Debian/), RetroPie-Setup quits on KDE Neon 20.04 with this message:
```
Unsupported OS

Distributor ID: Neon
Description:    KDE neon User Edition 5.20
Release:        20.04
Codename:       focal
```

I consider this a bug since it had already been fixed in 2016, see #1800.

**Comment by cmitu** [comment]
What's the output of
```
lsb_release -sidrc
```
on this distro ?

**Comment by Taranchul** [comment]
```
Neon
KDE neon User Edition 5.20
20.04
focal
```

**Comment by cmitu** [comment]
Can you try and see if the following modification to 'RetroPie-Setup/scriptmodules/system.sh` solves the problem:
``` diff
-        Ubuntu|neon|Pop)
+        Ubuntu|[N|n]eon|Pop)
             if compareVersions "$__os_release" lt 16.04; then
                 error="You need Ubuntu 16.04 or newer"
```

**Comment by STPKITT** [comment]
I experienced this issue right now. I had it working perfectly fine on the 18.04 based KDE Neon.

@cmitu: I tried this, exchanged the red line you posted with the green one and put
if compareVersions "$__os_release" lt 16.04; then
in front of
error="You need Ubuntu 16.04 or newer"
but the result was exactly the same as before.

Regardless of this specific case with KDE Neon I would propose the option to show the unsupported OS message but let the user force installation anyway since judging by how many Ubuntu-based distributions are out there many users will potentially experience this issue the way retropie_setup.sh is written currently.

**Comment by STPKITT** [comment]
I made it work by changing that one line to Ubuntu|Neon|neon|Pop).
Still option to force installation regardless is needed IMO.

**Comment by cmitu** [comment]
@STPKITT Try this, should work.
``` diff
-        Ubuntu|neon|Pop)
+        Ubuntu|[Nn]eon|Pop)
             if compareVersions "$__os_release" lt 16.04; then
                 error="You need Ubuntu 16.04 or newer"
```

**Comment by STPKITT** [comment]
I tried it and can confirm that it does work that way. So that change now just needs to find it's way into RetroPie proper.

**Comment by cmitu** [comment]
Sould be fixed with https://github.com/RetroPie/RetroPie-Setup/commit/44c33c1ffa85ab6b9bb2ddab0090670552945e25

**Comment by Taranchul** [comment]
Hello everyone,
sorry for the late answer. I somehow missed mitu's second reply 18 days ago, and when more people replied, RealLife™ held me firmly in its talons.

Thank you all for working on this in my absence, mitu's solution works fine on my Laptop with Neon 20.04. 👍
