### ISSUE TITLE
Retroarch old libsdl2

### ISSUE THREAD

**Issue by macinblack** [RetroPie/RetroPie-Setup#3343]
Hello, I figured that when I try to install retroarch by retropie setup, it install an old package libsdl2 (2.0.10+5rpi), but the lastest is 2.0.12+dfsg1-4. 

This creates a conflict between files in the Ubuntu Groovy Gorilla (20.10). " retroarch: libsdl2-2.0-0 (>= 2.0.12+dfsg1) but 2.0.10+5rpi is installed" and my terminal totatlly block any command.

Solved only with reinstall with:
$ dpkg -i '/home/user/Transferências/libsdl2-2.0-0_2.0.12+dfsg1-4_arm64.deb' 
$ sudo apt remove libsdl2-dev
$ sudo apt install libsdl2-dev

Now I have last version and fixed terminal.

Could you fix the installer?

**Comment by cmitu** [comment]
Ubuntu is not supported distro on a Pi and `aarch64` is not yet fully supported by RetroPie.

If you wish to use the distro's SDL library you need to set `own_sdl=0` in `/opt/retropie/configs/all/retropie.cfg` and re-run the installation of packages. Of course, there's no guarantee it would work or function properly, since it's not a supported or tested configuration.

**Comment by icolwell** [comment]
Correct me if I'm wrong, but I believe the line has changed to `own_sdl2=0` (note the 2).
Just an FYI for anyone else that may come across this.
