### ISSUE TITLE
raspberry pi 4 - retropie - Problem with 4k resolution

### ISSUE THREAD

**Issue by tarzinio** [RetroPie/RetroPie-Setup#3582]
Hi,

I have a problem with changing the z4k resolution to a lower one. The change by raspi-config does not work. Clicking on the items to change the resolution will reload the window and return to the raspi-config start screen. I tried config.txt by changing the group to 1:16 but that also didn't work. I tried to disable 4k completely with 
```
hdmi_max_pixel_freq:0=200000000
hdmi_max_pixel_freq:1=200000000
```
 but that didn't help either. Each time the retrops are loaded in 4k 30hz (Tv supports max 4k 59 / 60hz).

Does anyone know what could be wrong?

P.S. The system was updated.

Regards

**Comment by dankcushions** [comment]
please do not use github for retropie support as per the message when you create a new issue. instead use the forum.

as it happens, this issue was posted on the forum a few days ago: https://retropie.org.uk/forum/topic/33294/can-t-change-resolution - note that raspi-config is not created/maintained as part of retropie.
