### ISSUE TITLE
Add Sselph's Scraper as a module

### ISSUE THREAD

**Issue by HerbFargus** [RetroPie/RetroPie-Setup#945]
Mostly completed- just needs some work on a checklist to choose scrapers by system (function scraper_system)

```
#!/usr/bin/env bash

# This file is part of RetroPie.
# 
# (c) Copyright 2012-2015  Florian Müller (contact@petrockblock.com)
# 
# See the LICENSE.md file at the top-level directory of this distribution and 
# at https://raw.githubusercontent.com/RetroPie/RetroPie-Setup/master/LICENSE.md
#

rp_module_id="scraper"
rp_module_desc="Steven Selph's Scraper"
rp_module_menus="3+"

function scraper_install() {
echo "Downloading and Installing Scraper created by SSELPH..."
scraperVersion=$(wget -qO- https://api.github.com/repos/sselph/scraper/releases/latest | grep tag_name | sed -e 's/.*"tag_name": "\(.*\)".*/\1/')
    if isPlatform "rpi2"; then
        wget https://github.com/sselph/scraper/releases/download/$scraperVersion/scraper_rpi2.zip -q
        unzip scraper_rpi2.zip scraper -d /usr/local/bin/
        rm scraper_rpi2.zip
    else
        wget https://github.com/sselph/scraper/releases/download/$scraperVersion/scraper_rpi.zip -q
        unzip scraper_rpi.zip scraper -d /usr/local/bin/
        rm scraper_rpi.zip
    fi
    printMsgs "dialog" "$scraperVersion Scraper Installed"
}

function scraper_all() {
su pi -c "/usr/local/bin/scraper -scrape_all -thumb_only"
printMsgs "dialog" "All games scraped"
}

function scraper_system() {
#show scraper menu - ask user which console they would like to scrape					
romFolderList=$(grep "<path>" /etc/emulationstation/es_systems.cfg | sed "s/<path>//g" | sed "s/<\/path>//g" | sed "s/~/\/home\/pi/g" | awk '{print $0; print NR; print "OFF";}')
esSystemsList+=$romFolderList
    romFolders=$(whiptail --backtitle "PiAssist" --checklist "Select ROM Folders" 0 0 0 $romFolderList 3>&1 1>&2 2>&3)
    exit_status=$?
	romFolderAcutallySelected=true
	case $exit_status in
	$DIALOG_CANCEL)
	romFolderAcutallySelected=false
	;;
	$DIALOG_ESC)
	romFolderAcutallySelected=false
	;;
	esac
			if [ $romFolderAcutallySelected == true ] ; then
			romFolders=$(echo "$romFolders" | sed "s/\" \"/\\n/g" | sed "s/\"//g")
			echo "Scraping..."
			while read -r romFolder; do
			gameListXMLLocation="/home/pi/.emulationstation/gamelists/$(basename $romFolder)/gamelist.xml"
					#if mame, then we need to use the mame 
					if [[ $romFolder == *"mame"* ]]; then
					scraper -mame -mame_img "t,m,s" -image_dir="/home/pi/.emulationstation/downloaded_images/$(basename $romFolder)" -image_path="~/.emulationstation/downloaded_images/$(basename $romFolder)" -output_file="$gameListXMLLocation" -rom_dir="$romFolder"
						else
						scraper -image_dir="/home/pi/.emulationstation/downloaded_images/$(basename $romFolder)" -image_path="/home/pi/.emulationstation/downloaded_images/$(basename $romFolder)" -output_file="$gameListXMLLocation" -rom_dir="$romFolder"
							fi
								chown pi:pi "/home/pi/.emulationstation/downloaded_images/$(basename $romFolder)"
								#the scraper doesn't include the opening XML tag that is required
								if grep -q "<?xml" "$gameListXMLLocation" ; then
								#no action needs to occur
								echo "" > /dev/null
								else
									echo '<?xml version="1.0"?>' | cat - "$gameListXMLLocation" > temp && mv temp "$gameListXMLLocation"
								fi
									
							chown pi:pi "$gameListXMLLocation"
									
						find "/home/pi/.emulationstation/downloaded_images/$(basename $romFolder)" -exec chown pi:pi {} +
									
					if [[ -e temp ]]; then
					rm temp
					fi
									
					done <<< "$romFolders"
								
					printMsgs "dialog" "ROMs have been scraped."
							fi
						fi
					fi
}

function configure_scraper() {
    scraperVersion=$(wget -qO- https://api.github.com/repos/sselph/scraper/releases/latest | grep tag_name | sed -e 's/.*"tag_name": "\(.*\)".*/\1/')
    currentVersion=$(/usr/local/bin/scraper --version)

    while true; do
        cmd=(dialog --title "Steven Selph's Scraper."  --backtitle "$__backtitle" --menu "Latest Version:    $scraperVersion\nInstalled Version: $currentVersion" 22 76 16)
        options=(
            1 "Install Latest Scraper"
            2 "Scrape All Systems"
            3 "Scrape System(s) From List"
        )
        choice=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
        if [[ -n "$choice" ]]; then
            case $choice in
                1)
                    scraper_install
                    ;;
                2)
                    scraper_all
                    ;;
                3)
                    scraper_system
                    ;;
            esac
        else
            break
        fi
    done
}
```
adapted from https://github.com/Death259/PiAssist

**Comment by joolswills** [comment]
A good start - but will need some work to comply with our styleguide, and install folders should be part of /opt/retropie etc if possible. There are other fixes needing in regards to hardcoded paths/users etc

**Comment by HerbFargus** [comment]
I haven't tested it outside of /usr/local/bin but I'll test it out a bit later- I don't see any reason why it shouldnt work in opt/retropie

**Comment by joolswills** [comment]
I would prefer that we don't use code from the other project - partly because it doesn't fit with our styleguide, but also, because it was made as a separate project for a reason I guess - rather than contributing the stuff directly to this project. Also although we have a compatible licence our code requires everything gets copyrighted to the project also, which will likely conflict.

**Comment by HerbFargus** [comment]
that's a fair point- guess I need to work on my coding skills so I don't need to use other's projects as a crutch :P

**Comment by ProxyCell** [comment]
Can't this bash script just be ripped apart and formed to the RetroPie standards? I feel this is a HUGE improvement for the project.

**Comment by joolswills** [comment]
Well - It was already planned to implement this so don't panic - I've had it in mind for some time, so it will be done. It's not just a matter of our styleguide though regarding the above script - but I will write a scraper module when I have done with current tasks - All contributions are appreciated of course even if not accepted right away.

**Comment by robertybob** [comment]
@joolswills is there a particular reason this can't be integrated into Emulationstation to replace the default scraper that so many people still use and struggle with? If it's a case that the scraper is hard coded and you're not able to make any changes to it then that's fair enough :)

**Comment by joolswills** [comment]
Well work was done to integrate it, but then Aloshi got busy with real life.

I don't fancy maintaining large custom ES changes right now. Hopefully ES will become less fragmented in the future and be continued.

**Comment by Death259** [comment]
FYI, feel free to rip apart my code and add it to the official retropie code. I started my [PiAssist](https://github.com/Death259/PiAssist) project to fill some gaps that I thought existed. I didn't want to add it to RetroPie at the time, because I felt that my code would be far inferior to what you guys would want. After having worked with bash enough and seeing how you guys do things, I am going to start re-writing parts of my project so that they can be 100% integrated in RetorPie. Hopefully I can get things mostly there so that you guys won't have to do as much work to make it match your style. I've given Herbfargus the go ahead to do that as well. No since in reinventing the wheel, so have at it.

**Comment by Death259** [comment]
Here's my attempt at the scraper. It uses `$rootdir`, so it should work in the future if the main directory changes. I've made sure that the variable/function names and use of square brackets match what is requested in the style guide.

    #!/usr/bin/env bash

    # This file is part of RetroPie.
    # 
    # (c) Copyright 2012-2015  Florian Müller (contact@petrockblock.com)
    # 
    # See the LICENSE.md file at the top-level directory of this distribution and 
    # at https://raw.githubusercontent.com/RetroPie/RetroPie-Setup/master/LICENSE.md
    #

    rp_module_id="scraper"
    rp_module_desc="Steven Selph's Scraper"
    rp_module_menus="3+"
    rp_module_flags="nobin"

    function install_update_scraper() {    
        local scraper_version=$(wget -qO- https://api.github.com/repos/sselph/scraper/releases/latest | grep tag_name | sed -e 's/.*"tag_name": "\(.*\)".*/\1/')
        local scraper_location="$rootdir/supplementary/scraper"

        [[ ! -d "$scraper_location" ]] && mkdir "$scraper_location"

        #if scraper doesn't exist then download it
        local update_scraper=false
        if [[ -f "$scraper_location/scraper" ]] ; then
            local old_version=$("$scraper_location/scraper" -version 2> /dev/null)
            if [[ $? -ne 0 ]] || [[ "$scraper_version" != "$old_version" ]] ; then
                if (dialog --title "Update Scraper?" --yesno "Would you like to update the scraper script?" 0 0) then
                    update_scraper=true
                fi
            fi
        fi

        if [[ ! -f "$scraper_location/scraper" ]] || [[ $update_scraper == true ]] ; then
            #if raspberrypi1 then download the build for raspberrypi1
            if grep -q ARMv7 /proc/cpuinfo ; then
                wget https://github.com/sselph/scraper/releases/download/$scraper_version/scraper_rpi2.zip -q -O "$scraper_location/../scraper_rpi2.zip"
                unzip -qq -o "$scraper_location/../scraper_rpi2.zip" scraper -d "$scraper_location"
                rm "$scraper_location/../scraper_rpi2.zip"
            else
                wget https://github.com/sselph/scraper/releases/download/$scraper_version/scraper_rpi.zip -q -O "$scraper_location/../scraper_rpi.zip"
                unzip -qq -o "$scraper_location/../scraper_rpi.zip" scraper -d "$scraper_location"
                rm "$scraper_location/../scraper_rpi.zip"
            fi
        fi
    }

    function scrape_all_roms_scraper() {
        local scraper_location="$rootdir/supplementary/scraper"
        
        install_update_scraper
    
        $scraper_location/scraper -scrape_all -thumb_only
    }


    function scrape_specific_systems_scraper() {
        local scraper_location="$rootdir/supplementary/scraper"
        install_update_scraper
    
        local system_names=() 
        local system_name 
        local paths=() 
        local path
        local options=()
        i=0
        while read system_name; read path; do 
            system_names+=("$system_name") 
            paths+=("$path") 
            options+=("$i" "$system_name" OFF)
            ((i++))
        done < <(get_rom_information_from_es_systems_config)
    
        if [[ ${#system_names[@]} -eq 0 ]] ; then
            printMsgs "dialog" "No rom folders were found."
        else
            local cmd=(whiptail --backtitle "PiAssist" --checklist "Select ROM Folders" 22 76 16) 
            choices+=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty) 
            [[ -z "$choices" ]] && return
        
            for choice in $choices
            do
                choice=$(echo $choice | sed 's/"//g')
                gamelist_folder_name=$(echo ${system_names[$choice]})
                romFolder=$(echo ${paths[$choice]} | sed 's/~/\/home\/pi/g')
                gameListXMLLocation="/home/pi/.emulationstation/gamelists/$gamelist_folder_name/gamelist.xml"
                #if mame, then we need to use the mame 
                if [[ $romFolder == *"mame"* ]]; then
                    scraper -mame -mame_img "t,m,s" -image_dir="/home/pi/.emulationstation/downloaded_images/$gamelist_folder_name" -image_path="~/.emulationstation/downloaded_images/$gamelist_folder_name" -output_file="$gameListXMLLocation" -rom_dir="$romFolder"
                else
                    scraper -image_dir="/home/pi/.emulationstation/downloaded_images/$gamelist_folder_name" -image_path="/home/pi/.emulationstation/downloaded_images/$gamelist_folder_name" -output_file="$gameListXMLLocation" -rom_dir="$romFolder"
                fi
                chown pi:pi "/home/pi/.emulationstation/downloaded_images/$gamelist_folder_name"
                #the scraper doesn't include the opening XML tag that is required. If that gets fixed in the future, we wont' have to change anything
                [[ ! grep -q "<?xml" "$gameListXMLLocation" ]] && echo '<?xml version="1.0"?>' | cat - "$gameListXMLLocation" > temp && mv temp "$gameListXMLLocation"
                        
                chown pi:pi "$gameListXMLLocation"
            
                find "/home/pi/.emulationstation/downloaded_images/$gamelist_folder_name" -exec chown pi:pi {} +
            
                if [[ -e temp ]]; then
                    rm temp
                fi
            done
        
            printMsgs "dialog" "ROMS have been scraped. You can  now get back into Emulation Station."
        fi
    }

    function sselph_rom_scraper() { 
        while true; do
            local cmd=(dialog --backtitle "$__backtitle" --menu "Scraper by Steven Selph" 22 76 16) 
            local options=( 
                1 "Scrape All Systems" 
                2 "Scrape Specific Systems" 
            ) 
            local choice=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty) 
            if [[ -n "$choice" ]]; then 
                case $choice in 
                    1) 
                        scrape_all_roms_scraper 
                        ;; 
                    2) 
                        scrape_specific_systems_scraper 
                        ;; 
                esac 
            else 
                break 
            fi 
        done 
    }

**Comment by joolswills** [comment]
Thanks but this is going to more work before it can be accepted. 

please use "$md_inst" instead of $rootdir/supplementary/scraper - you dont need another variable for it

your variable names are a little overly verbose. gamelist_folder_name could just be folder, as the context is already clear from the function/loop

there are camelcase vars that should be changed

there are hardcoded paths like /home/pi which should be $home or hardcoded user pi which should be $user.

Where is get_rom_information_from_es_systems_config defined ? this function name should be shortened.

regarding the bug mentioned with the xml  tag - has this been reported upstream ?

Ideally the module would build from source, and not use 3rd party binaries. at least so we can easily rebuild new binaries etc (in the same way as emulator modules or emulationstation)

**Comment by joolswills** [comment]
Regarding source, the meantime if installing binaries, it should use the "isPlatform" call to check which platform

```
if isPlatform "rpi1"; then
if isPlatform "rpi2"; then
```

**Comment by joolswills** [comment]
I'm currently working on this btw - started off with the above code, but looks like I will rewrite most of it.

Making an assumption that roms are in ~/RetroPie/roms too - instead of parsing gameslists (when we possibly move to ES using sqlite3 I don't want to rewrite it). If someone has put their roms elsewhere and modified ES configs, they will need to run it manually. Keeps it simple then.

**Comment by HerbFargus** [comment]
Thanks @joolswills I was mucking with it last night and could only get the scrape all function to work (which sselph's just incorporated mame into) much appreciated.

**Comment by joolswills** [comment]
What is the preferable location for gamelists/images ? in the rom folders or in .emulationstation ? by default the scraper would use each rom folder, so maybe that is best?

**Comment by HerbFargus** [comment]
Yeah sselph's scraper keeps the images and gamelists in their respective rom folders

**Comment by robertybob** [comment]
Could it be changed to Emulationstation? The systems that cannot currently by scraped will have their gamelists and images (from the built in scraper) there anyway. May get confusing having them in two different places.

**Comment by joolswills** [comment]
but easier to backup lists and roms if they live with the roms themselves. but maybe I'll make it an option.

**Comment by HerbFargus** [comment]
yeah it does make it easier to back up in each rom folder, but options are a good idea.

**Comment by joolswills** [comment]
Interested in hearing peoples preferred configurations for the scraper, such as if they use thumb-only, or prefer screenshots over marquees etc (please give me your commandline params)

**Comment by sselph** [comment]
This is great!

The reason to use the binary instead of source is because debian/wheezy has a very old version of Go in it's repository and it is unable to compile my code. You could use the unofficial binary of Go at http://dave.cheney.net/unofficial-arm-tarballs which would allow you to compile. It would require a ~50MB upfront download but would make upgrading fast and use very little bandwidth.

**Comment by joolswills** [comment]
thanks - and thanks for your work. This probably should have been added a long time ago, but then there was some hope that your scraper code would make it into ES, but unfortunately Aloshi is very busy with real life it seem.

I'll probably just wait until we move to jessie, and then add an option to build from source, but I'm quite ok using your binaries for now :-)

**Comment by joolswills** [comment]
(I know there is an ES branch with your code in - what stage did it get to ?) ? I'd be happy to take in pull requests against our ES fork for retropie.

**Comment by sselph** [comment]
The code is in the unstable branch of ES. It is functional but I haven't been keeping it to the same level as my code since my first pull request to make a fix has been there since March. It is missing PSX, Dreamcast, and ScummVM support which was added later. It is missing MAME support which in my code is just rip off of a PR from ES.

**Comment by sselph** [comment]
I forgot mention the UX could be improved. There is a third scraper now "TheGamesDB w/SHA1" and to make it work well you turn off the "user decides on conflict" otherwise you have to hit skip when there isn't a match. That was something Aloshi wanted to fix where you have multiple scrapers chosen and it would work through a progression like a platform specific scraper then do an automatic scraper then a manual scraper.

I think it is also slightly slower since it is updating UI elements as it progresses vs printing a log entry.

**Comment by FlyingPikachu** [comment]
Man, this sure would be nice!

**Comment by joolswills** [comment]
scraper module now has ability to enable/disable thumb-only - and it has been moved out of the experimental menu

**Comment by sselph** [comment]
Just FYI, not using -thumb_only and using -workers 4 might lead to the raspberry pi running out of memory or cause paging. Each worker uses ~125 MB to process the full sized images since it decompresses the image then recompresses. More detail in this issue https://github.com/sselph/scraper/issues/61

**Comment by joolswills** [comment]
thanks. We can document it or reduce workers perhaps depending on free ram - should be ok on a 1GB ram machines though.

**Comment by joolswills** [comment]
By default it is set to use "-thumb_only" also.
