### ISSUE TITLE
Can this be done? As a future update..(enhancement)

### ISSUE THREAD

**Issue by Haris1977** [RetroPie/RetroPie-Setup#977]
I pulled it from within RecallBox (configure menu for p2,p3 and p4):

http://www.2shared.com/photo/UDXeEWYg/Controller.html

+1 for this. I think it needs to be implemented into future updates..

(I think this post's label is "enhancement" sorry..)

**Comment by Tele42** [comment]
It's generally considered good form to type out (almost) everything so that an issue report stands on it's own without any external references, that way the issue report is still coherent if the other website removes whatever content in the future. Having said that, this issue seems to be for Emulationstation's upstream development (https://github.com/Aloshi/EmulationStation/issues).

**Comment by joolswills** [comment]
They have some custom controller stuff in recallbox. We don't yet have any scripts to configure fba etc, so no point in player 2-4 controls yet, but the code iabove is specific to recallbox, and would not work without changes against our already modified es I guess. (We have some of our own custom controller stuff)

**Comment by Haris1977** [comment]
As i am little baffled here..can anyone explain how to setup a second (different) controller? If i do it from within ES menu-having plugged in my 1rst controller-will i be able to configure the second one? or should i remove my first gamepad and then do it?

**Comment by joolswills** [comment]
You can just go to the ES menu and configure another controller, and it will set up a retroarch configuration for it, and make it work with ES too.

**Comment by joolswills** [comment]
You can leave your first controller plugged in.

**Comment by Haris1977** [comment]
Thanks:)
